// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// unNormedMargLogLikeCpp
double unNormedMargLogLikeCpp(double phi, double shift, int z11, int z12, int z21, int z22, int m011, int m012, int m021, int m022, int y01, int y02, int N1, int N2, int N01, int N02);
RcppExport SEXP _poisDoubleSamp_unNormedMargLogLikeCpp(SEXP phiSEXP, SEXP shiftSEXP, SEXP z11SEXP, SEXP z12SEXP, SEXP z21SEXP, SEXP z22SEXP, SEXP m011SEXP, SEXP m012SEXP, SEXP m021SEXP, SEXP m022SEXP, SEXP y01SEXP, SEXP y02SEXP, SEXP N1SEXP, SEXP N2SEXP, SEXP N01SEXP, SEXP N02SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type shift(shiftSEXP);
    Rcpp::traits::input_parameter< int >::type z11(z11SEXP);
    Rcpp::traits::input_parameter< int >::type z12(z12SEXP);
    Rcpp::traits::input_parameter< int >::type z21(z21SEXP);
    Rcpp::traits::input_parameter< int >::type z22(z22SEXP);
    Rcpp::traits::input_parameter< int >::type m011(m011SEXP);
    Rcpp::traits::input_parameter< int >::type m012(m012SEXP);
    Rcpp::traits::input_parameter< int >::type m021(m021SEXP);
    Rcpp::traits::input_parameter< int >::type m022(m022SEXP);
    Rcpp::traits::input_parameter< int >::type y01(y01SEXP);
    Rcpp::traits::input_parameter< int >::type y02(y02SEXP);
    Rcpp::traits::input_parameter< int >::type N1(N1SEXP);
    Rcpp::traits::input_parameter< int >::type N2(N2SEXP);
    Rcpp::traits::input_parameter< int >::type N01(N01SEXP);
    Rcpp::traits::input_parameter< int >::type N02(N02SEXP);
    rcpp_result_gen = Rcpp::wrap(unNormedMargLogLikeCpp(phi, shift, z11, z12, z21, z22, m011, m012, m021, m022, y01, y02, N1, N2, N01, N02));
    return rcpp_result_gen;
END_RCPP
}
// unNormedMargLogLikeMaxLogTermCpp
double unNormedMargLogLikeMaxLogTermCpp(double phi, int z11, int z12, int z21, int z22, int m011, int m012, int m021, int m022, int y01, int y02, int N1, int N2, int N01, int N02);
RcppExport SEXP _poisDoubleSamp_unNormedMargLogLikeMaxLogTermCpp(SEXP phiSEXP, SEXP z11SEXP, SEXP z12SEXP, SEXP z21SEXP, SEXP z22SEXP, SEXP m011SEXP, SEXP m012SEXP, SEXP m021SEXP, SEXP m022SEXP, SEXP y01SEXP, SEXP y02SEXP, SEXP N1SEXP, SEXP N2SEXP, SEXP N01SEXP, SEXP N02SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< int >::type z11(z11SEXP);
    Rcpp::traits::input_parameter< int >::type z12(z12SEXP);
    Rcpp::traits::input_parameter< int >::type z21(z21SEXP);
    Rcpp::traits::input_parameter< int >::type z22(z22SEXP);
    Rcpp::traits::input_parameter< int >::type m011(m011SEXP);
    Rcpp::traits::input_parameter< int >::type m012(m012SEXP);
    Rcpp::traits::input_parameter< int >::type m021(m021SEXP);
    Rcpp::traits::input_parameter< int >::type m022(m022SEXP);
    Rcpp::traits::input_parameter< int >::type y01(y01SEXP);
    Rcpp::traits::input_parameter< int >::type y02(y02SEXP);
    Rcpp::traits::input_parameter< int >::type N1(N1SEXP);
    Rcpp::traits::input_parameter< int >::type N2(N2SEXP);
    Rcpp::traits::input_parameter< int >::type N01(N01SEXP);
    Rcpp::traits::input_parameter< int >::type N02(N02SEXP);
    rcpp_result_gen = Rcpp::wrap(unNormedMargLogLikeMaxLogTermCpp(phi, z11, z12, z21, z22, m011, m012, m021, m022, y01, y02, N1, N2, N01, N02));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_poisDoubleSamp_unNormedMargLogLikeCpp", (DL_FUNC) &_poisDoubleSamp_unNormedMargLogLikeCpp, 16},
    {"_poisDoubleSamp_unNormedMargLogLikeMaxLogTermCpp", (DL_FUNC) &_poisDoubleSamp_unNormedMargLogLikeMaxLogTermCpp, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_poisDoubleSamp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
